version: 2.1

jobs:
  test:
    parameters:
      ruby-version:
        type: string
    docker:
      - image: cimg/ruby:<< parameters.ruby-version >>-browsers
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec rspec

workflows:
  all-tests:
    jobs:
      - test:
          matrix:
            parameters:
              ruby-version: ["3.0.6", "3.1.4", "3.2.2"]
